name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - "11-set-up-cicd"

jobs:
  deploy:
    name: Run Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - name: checkout and change directory
        run: |
          cd terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: Deploy to AWS with Terraform
        run: terraform init && terraform apply -auto-approve
